import { connectDB } from "@/lib/databaseconnection";
import CounterModel from "@/models/Counter.model";
import { getRestaurantSettings } from "@/lib/settings.server";

const POS_SEQUENCE_KEY = "pos_order_seq";
const POS_SEQUENCE_START = 100000;
const POS_PREFIX_FALLBACK = "SL-";

/**
 * Atomically returns the next human-friendly POS order number, e.g.
 * "SL-100001", "SL-100002", ... using the admin-configured prefix
 * (RestaurantSettings.orders.posOrderPrefix) when set. Website orders
 * are untouched — they keep the existing "ORD-<random hex>" format
 * generated by Order.model.js's own pre-validate hook, which only
 * fires when orderNumber hasn't already been set (as it is here,
 * before create()).
 */
export async function getNextPosOrderNumber() {
  await connectDB();

  const [counter, settings] = await Promise.all([
    CounterModel.findOneAndUpdate(
      { _id: POS_SEQUENCE_KEY },
      { $inc: { seq: 1 } },
      { upsert: true, returnDocument: "after" },
    ),
    getRestaurantSettings(),
  ]);

  const prefix = settings.orders?.posOrderPrefix || POS_PREFIX_FALLBACK;

  return `${prefix}${POS_SEQUENCE_START + counter.seq}`;
}
